//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETradingEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessOwner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BusinessOwner()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public short CompanyId { get; set; }
        public string CompanyName { get; set; }
        public string OwnerName { get; set; }
        public string OwnerEmail { get; set; }
        public string CompanyPasscode { get; set; }
        public System.DateTime DateOfIncorporation { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<short> CategoryId { get; set; }
        public string CompanyAddress { get; set; }
        public int SharePrice { get; set; }
        public short NoOfShares { get; set; }
    
        public virtual CategoryDetail CategoryDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
